package markers;

public enum Stage {
    OFF,
    TAINT_FIELDS_GRAPH_BUILD,
    FRAGMENT_SEARCHING_SINGLE,
    FRAGMENT_SEARCHING,
    FRAGMENT_LINKING,
    IOCD_GENERATING,
    IOCD_SUPPLEMENT_INFER
}
